import torch
import numpy as np
import torch.nn.functional as F
from classifier import CNN
from utils import load_dataset
import json
import argparse
import os

# 配置
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DATASET_NAME = os.getenv("DATASET_NAME", "CIFAR10")
MODEL_ARCH = os.getenv("MODEL_ARCH", "CNN7")
SHADOW_CLUSTER = int(os.getenv("SHADOW_CLUSTER", "3000"))
SHADOW_MODEL_PATH = os.getenv(
    "SHADOW_MODEL_PATH",
    f"python_server/CIFAR10/shadow/{SHADOW_CLUSTER}/best_checkpoint_ep.pth",
)
SHADOW_CONFIG_OUTPUT = os.getenv("SHADOW_CONFIG_OUTPUT", "shadow_config.json")
BATCH_SIZE = int(os.getenv("BATCH_SIZE", "128"))


def estimate_tau_opt(member_losses, non_member_losses):
    all_losses = np.concatenate([member_losses, non_member_losses])
    candidates = np.unique(np.percentile(all_losses, np.linspace(1, 99, 300)))

    best_tau = float(np.median(all_losses))
    best_acc = -1.0

    for tau in candidates:
        tp = np.sum(member_losses < tau)
        tn = np.sum(non_member_losses >= tau)
        acc = (tp + tn) / (len(member_losses) + len(non_member_losses))
        if acc > best_acc:
            best_acc = acc
            best_tau = float(tau)

    return best_tau, float(best_acc)

def get_losses(model, loader):
    model.eval()
    losses = []
    print(f"[*] Calculating loss for {len(loader.dataset)} samples...")
    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(DEVICE), target.to(DEVICE)
            output = model(data)
            # 计算 CrossEntropy Loss (reduction='none' 拿每个样本的 loss)
            loss = F.cross_entropy(output, target, reduction='none')
            losses.extend(loss.cpu().numpy().tolist())
    return np.array(losses)

def main():
    if not os.path.exists(SHADOW_MODEL_PATH):
        print(f"[!] 找不到影子模型: {SHADOW_MODEL_PATH}")
        print("请先运行 main.py (action=1) 训练影子模型！")
        return

    # 1. 加载影子模型
    print("[*] Loading Shadow Model...")
    model = CNN(MODEL_ARCH, DATASET_NAME).to(DEVICE)
    # 偷懒直接加载 state_dict (假设你是最新的 server.py 标准保存的)
    ckpt = torch.load(SHADOW_MODEL_PATH, map_location=DEVICE)
    if 'state_dict' in ckpt: ckpt = ckpt['state_dict']
    
    clean_ckpt = {}
    for k, v in ckpt.items():
        if k.startswith('module.'): clean_ckpt[k[7:]] = v
        else: clean_ckpt[k] = v
    model.load_state_dict(clean_ckpt)

    # 2. 加载影子数据
    # 使用 mode='shadow' 来获取用来训练 Shadow 的数据 (Members)
    # utils.py 逻辑：mode='shadow' 返回的 train_loader 是 Member
    # 我们还需要 Non-member (shadow 的 test set)
    print("[*] Loading Datasets...")
    args = argparse.Namespace(batch_size=BATCH_SIZE)
    
    # 获取 Shadow 的 Member (即 Shadow 的训练集)
    # 注意：根据 utils.py 逻辑，Train_Shadow_Model 用的是 load_dataset(..., mode='shadow')
    shadow_train_loader = load_dataset(args, DATASET_NAME, cluster=SHADOW_CLUSTER, mode='shadow')
    
    # 获取 Shadow 的 Non-Member (我们复用 target 的 test loader 作为通用的 non-member 池)
    # 因为 Shadow 的训练数据是专门切出来的，Test 数据可以是公共的测试集
    _, test_loader = load_dataset(args, DATASET_NAME, cluster=SHADOW_CLUSTER, mode='target')

    # 3. 计算 Loss 分布
    member_losses = get_losses(model, shadow_train_loader)
    non_member_losses = get_losses(model, test_loader)

    # 4. 计算统计指标
    print(f"[*] Analyzing distributions...")
    print(f"    Member Loss Mean: {np.mean(member_losses):.4f}")
    print(f"    Non-Mem Loss Mean: {np.mean(non_member_losses):.4f}")

    tau_95 = float(np.percentile(non_member_losses, 5))
    tau_opt, best_acc = estimate_tau_opt(member_losses, non_member_losses)

    if tau_95 > tau_opt:
        tau_95, tau_opt = tau_opt, tau_95

    result = {
        "tau_95": tau_95,
        "tau_opt": tau_opt,
        "threshold": tau_opt,
        "mean_member_loss": float(np.mean(member_losses)),
        "mean_non_member_loss": float(np.mean(non_member_losses)),
        "std_member_loss": float(np.std(member_losses)),
        "std_non_member_loss": float(np.std(non_member_losses)),
        "best_split_acc": best_acc,
        "description": "Generated by calc_thresholds.py"
    }

    # 5. 保存
    with open(SHADOW_CONFIG_OUTPUT, 'w') as f:
        json.dump(result, f, indent=4)
    
    print(f"[+] 配置生成完毕！{SHADOW_CONFIG_OUTPUT}: {result}")

if __name__ == '__main__':
    main()
